"""
Implements: Section 3 -- services/scope_allowed.json ("Generated by
preflight from scope.yaml") and the "scope_json_gen" preflight check
(cli/main.py comment block, Section 3).
Also implements (Week 2 addition): Section 3's scope.yaml comment
block's `program_type` field ("bug_bounty" | "vdp") -- `load_program_type`
below is a second, small reader over the same scope.yaml file, added
here rather than as a third parallel YAML parser elsewhere, so this
module stays the single place that knows how to read configs/scope.yaml.
Consumed by core/governance/safety_gate.py's VDP tier-cap enforcement
(Section 10.1, R-L5 fix).

Also implements (Week 6 addition, docs/DECISIONS.md item 65): Section
3's scope.yaml comment block's `credential_validation_allowlist` block
(R-H4 fix) -- `load_credential_validation_allowlist` below is a third
reader over the same file, same reasoning as `load_program_type`'s own
addition note above: one place that knows how to read configs/scope.yaml,
not a third parallel parser. Consumed by
core/governance/scope_enforcer.py's `is_allowed()` exemption branch.
Blueprint: bb_agent_v6.6_final_blueprint.md

Reads configs/scope.yaml's `scope_domains` list and writes
services/scope_allowed.json in the shape both Go services load via
their `-scope-json` flag (Section 10.8's ScopeGuard.AllowedPatterns /
scope_guard.go's scopeAllowedDoc).
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

from core.ontology.scope import CredentialValidationAllowlist

_VALID_PROGRAM_TYPES = frozenset({"bug_bounty", "vdp"})


class ScopeConfigError(Exception):
    """Raised when scope.yaml is missing, malformed, or has an empty
    scope_domains list."""


@dataclass(frozen=True)
class ScopeGenerationResult:
    """Result of a scope_allowed.json generation run.

    Attributes:
        output_path: Where scope_allowed.json was written.
        pattern_count: Number of patterns written.
        patterns: The exact patterns written, in source order.
    """

    output_path: Path
    pattern_count: int
    patterns: list[str]


def load_scope_domains(scope_yaml_path: Path) -> list[str]:
    """Loads and validates the `scope_domains` list from scope.yaml.

    Args:
        scope_yaml_path: Path to configs/scope.yaml.

    Returns:
        The scope_domains list, in file order, duplicates removed.

    Raises:
        ScopeConfigError: If the file is missing, is not valid YAML, has
            no `scope_domains` key, or `scope_domains` is empty or
            contains non-string entries.
    """
    if not scope_yaml_path.is_file():
        raise ScopeConfigError(f"scope.yaml not found at {scope_yaml_path}")

    try:
        raw: Any = yaml.safe_load(scope_yaml_path.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        raise ScopeConfigError(f"scope.yaml is not valid YAML: {exc}") from exc

    if not isinstance(raw, dict) or "scope_domains" not in raw:
        raise ScopeConfigError(f"scope.yaml at {scope_yaml_path} has no 'scope_domains' key")

    domains = raw["scope_domains"]
    if not isinstance(domains, list) or not domains:
        raise ScopeConfigError("scope.yaml 'scope_domains' must be a non-empty list")
    if not all(isinstance(d, str) and d.strip() for d in domains):
        raise ScopeConfigError("scope.yaml 'scope_domains' must contain only non-empty strings")

    # De-duplicate while preserving order (stable for regeneration, which
    # matters because scope_allowed.json feeds BOTH Go services
    # independently -- Section 10.8 -- and should not drift between runs
    # just because dict/set ordering happened to differ).
    seen: set[str] = set()
    ordered: list[str] = []
    for d in domains:
        if d not in seen:
            seen.add(d)
            ordered.append(d)
    return ordered


def load_program_type(scope_yaml_path: Path) -> str:
    """Loads and validates the `program_type` field from scope.yaml.

    Section 3's scope.yaml comment block (R-L5 fix): "bug_bounty": max_tier
    = TIER_C (per explicit rules in Section 10.1); "vdp": max_tier = TIER_B
    (safety_gate.py caps at TIER_B).

    Args:
        scope_yaml_path: Path to configs/scope.yaml.

    Returns:
        Either "bug_bounty" or "vdp".

    Raises:
        ScopeConfigError: If the file is missing, is not valid YAML, has
            no `program_type` key, or the value is anything other than
            "bug_bounty" or "vdp" -- fail-closed, since an unrecognized
            program_type must not silently fall through to whichever
            branch a caller's if/else happens to default to.
    """
    if not scope_yaml_path.is_file():
        raise ScopeConfigError(f"scope.yaml not found at {scope_yaml_path}")

    try:
        raw: Any = yaml.safe_load(scope_yaml_path.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        raise ScopeConfigError(f"scope.yaml is not valid YAML: {exc}") from exc

    if not isinstance(raw, dict) or "program_type" not in raw:
        raise ScopeConfigError(f"scope.yaml at {scope_yaml_path} has no 'program_type' key")

    program_type = raw["program_type"]
    if program_type not in _VALID_PROGRAM_TYPES:
        raise ScopeConfigError(
            f"scope.yaml 'program_type' must be one of {sorted(_VALID_PROGRAM_TYPES)}, got {program_type!r}"
        )
    return program_type


def load_credential_validation_allowlist(scope_yaml_path: Path) -> CredentialValidationAllowlist:
    """Loads and validates the `credential_validation_allowlist` block
    from scope.yaml.

    Section 3's scope.yaml comment block (R-H4 fix): the
    `hardcoded_credentials.py`-only exemption letting
    `core.governance.scope_enforcer.is_allowed()` permit read-only GET
    calls to external credential-validation APIs outside `scope_domains`.

    Args:
        scope_yaml_path: Path to configs/scope.yaml.

    Returns:
        A CredentialValidationAllowlist built from the block's `enabled`
        and `external_apis` values.

    Raises:
        ScopeConfigError: If the file is missing, is not valid YAML, has
            no `credential_validation_allowlist` key, the block is not a
            mapping, `enabled` is missing or not a boolean, or
            `external_apis` is missing, not a list, or contains a
            non-string / empty-string entry -- fail-closed, mirroring
            `load_program_type`'s validation strictness. An empty
            `external_apis` list (with `enabled: true`) is valid: it
            means the exemption is switched on but currently matches no
            host, not a config error.
    """
    if not scope_yaml_path.is_file():
        raise ScopeConfigError(f"scope.yaml not found at {scope_yaml_path}")

    try:
        raw: Any = yaml.safe_load(scope_yaml_path.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        raise ScopeConfigError(f"scope.yaml is not valid YAML: {exc}") from exc

    if not isinstance(raw, dict) or "credential_validation_allowlist" not in raw:
        raise ScopeConfigError(
            f"scope.yaml at {scope_yaml_path} has no 'credential_validation_allowlist' key"
        )

    block = raw["credential_validation_allowlist"]
    if not isinstance(block, dict):
        raise ScopeConfigError("scope.yaml 'credential_validation_allowlist' must be a mapping")

    if "enabled" not in block:
        raise ScopeConfigError("scope.yaml 'credential_validation_allowlist.enabled' key is missing")
    enabled = block["enabled"]
    if not isinstance(enabled, bool):
        raise ScopeConfigError("scope.yaml 'credential_validation_allowlist.enabled' must be a boolean")

    if "external_apis" not in block:
        raise ScopeConfigError(
            "scope.yaml 'credential_validation_allowlist.external_apis' key is missing"
        )
    external_apis = block["external_apis"]
    if not isinstance(external_apis, list) or not all(
        isinstance(a, str) and a.strip() for a in external_apis
    ):
        raise ScopeConfigError(
            "scope.yaml 'credential_validation_allowlist.external_apis' must be a list of non-empty strings"
        )

    return CredentialValidationAllowlist(enabled=enabled, external_apis=list(external_apis))


def generate_scope_allowed_json(scope_yaml_path: Path, output_path: Path) -> ScopeGenerationResult:
    """Generates services/scope_allowed.json from configs/scope.yaml.

    This implements the "scope_json_gen" preflight check's action
    (Section 3, cli/main.py comment block): "generates
    services/scope_allowed.json from scope.yaml".

    Args:
        scope_yaml_path: Path to configs/scope.yaml.
        output_path: Path to write services/scope_allowed.json to.

    Returns:
        A ScopeGenerationResult describing what was written.

    Raises:
        ScopeConfigError: Propagated from load_scope_domains.
    """
    patterns = load_scope_domains(scope_yaml_path)

    document = {
        "allowed_patterns": patterns,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source": str(scope_yaml_path),
    }

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8")

    return ScopeGenerationResult(output_path=output_path, pattern_count=len(patterns), patterns=patterns)


def main() -> int:
    """CLI entry point: python3 -m core.governance.scope_config_generator."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--scope-yaml", type=Path, default=Path("configs/scope.yaml"))
    parser.add_argument("--output", type=Path, default=Path("services/scope_allowed.json"))
    args = parser.parse_args()

    try:
        result = generate_scope_allowed_json(args.scope_yaml, args.output)
    except ScopeConfigError as exc:
        print(f"[SCOPE_JSON_GEN_FAILED] {exc}")
        return 1

    print(f"[SCOPE_JSON_GEN_OK] wrote {result.pattern_count} pattern(s) to {result.output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
