"""
Implements: Section 3 -- services/scope_allowed.json ("Generated by
preflight from scope.yaml") and the "scope_json_gen" preflight check
(cli/main.py comment block, Section 3).
Blueprint: bb_agent_v6.6_final_blueprint.md

Reads configs/scope.yaml's `scope_domains` list and writes
services/scope_allowed.json in the shape both Go services load via
their `-scope-json` flag (Section 10.8's ScopeGuard.AllowedPatterns /
scope_guard.go's scopeAllowedDoc).
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml


class ScopeConfigError(Exception):
    """Raised when scope.yaml is missing, malformed, or has an empty
    scope_domains list."""


@dataclass(frozen=True)
class ScopeGenerationResult:
    """Result of a scope_allowed.json generation run.

    Attributes:
        output_path: Where scope_allowed.json was written.
        pattern_count: Number of patterns written.
        patterns: The exact patterns written, in source order.
    """

    output_path: Path
    pattern_count: int
    patterns: list[str]


def load_scope_domains(scope_yaml_path: Path) -> list[str]:
    """Loads and validates the `scope_domains` list from scope.yaml.

    Args:
        scope_yaml_path: Path to configs/scope.yaml.

    Returns:
        The scope_domains list, in file order, duplicates removed.

    Raises:
        ScopeConfigError: If the file is missing, is not valid YAML, has
            no `scope_domains` key, or `scope_domains` is empty or
            contains non-string entries.
    """
    if not scope_yaml_path.is_file():
        raise ScopeConfigError(f"scope.yaml not found at {scope_yaml_path}")

    try:
        raw: Any = yaml.safe_load(scope_yaml_path.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        raise ScopeConfigError(f"scope.yaml is not valid YAML: {exc}") from exc

    if not isinstance(raw, dict) or "scope_domains" not in raw:
        raise ScopeConfigError(f"scope.yaml at {scope_yaml_path} has no 'scope_domains' key")

    domains = raw["scope_domains"]
    if not isinstance(domains, list) or not domains:
        raise ScopeConfigError("scope.yaml 'scope_domains' must be a non-empty list")
    if not all(isinstance(d, str) and d.strip() for d in domains):
        raise ScopeConfigError("scope.yaml 'scope_domains' must contain only non-empty strings")

    # De-duplicate while preserving order (stable for regeneration, which
    # matters because scope_allowed.json feeds BOTH Go services
    # independently -- Section 10.8 -- and should not drift between runs
    # just because dict/set ordering happened to differ).
    seen: set[str] = set()
    ordered: list[str] = []
    for d in domains:
        if d not in seen:
            seen.add(d)
            ordered.append(d)
    return ordered


def generate_scope_allowed_json(scope_yaml_path: Path, output_path: Path) -> ScopeGenerationResult:
    """Generates services/scope_allowed.json from configs/scope.yaml.

    This implements the "scope_json_gen" preflight check's action
    (Section 3, cli/main.py comment block): "generates
    services/scope_allowed.json from scope.yaml".

    Args:
        scope_yaml_path: Path to configs/scope.yaml.
        output_path: Path to write services/scope_allowed.json to.

    Returns:
        A ScopeGenerationResult describing what was written.

    Raises:
        ScopeConfigError: Propagated from load_scope_domains.
    """
    patterns = load_scope_domains(scope_yaml_path)

    document = {
        "allowed_patterns": patterns,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source": str(scope_yaml_path),
    }

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8")

    return ScopeGenerationResult(output_path=output_path, pattern_count=len(patterns), patterns=patterns)


def main() -> int:
    """CLI entry point: python3 -m core.governance.scope_config_generator."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--scope-yaml", type=Path, default=Path("configs/scope.yaml"))
    parser.add_argument("--output", type=Path, default=Path("services/scope_allowed.json"))
    args = parser.parse_args()

    try:
        result = generate_scope_allowed_json(args.scope_yaml, args.output)
    except ScopeConfigError as exc:
        print(f"[SCOPE_JSON_GEN_FAILED] {exc}")
        return 1

    print(f"[SCOPE_JSON_GEN_OK] wrote {result.pattern_count} pattern(s) to {result.output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
